<?php

namespace AppBundle\Entity;

/**
 * JailbreakRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JailbreakRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * find the most recent jailbroken firmware
     *
     * @return AppBundle\Entity\Jailbreak
     */
    public function findByLatestJailbreak()
    {

    }
}
